//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Account {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AccountViewRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AccountViewRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Account.View.AccountViewRes", typeof(AccountViewRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Аккаунт не был создан. Пожалуйста, исправьте ошибки и попробуйте снова.
        /// </summary>
        public static string AccountCreationWasUnsuccessfulPleaseCorrectTheErrorsAndTryAgain {
            get {
                return ResourceManager.GetString("AccountCreationWasUnsuccessfulPleaseCorrectTheErrorsAndTryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Учётные данные.
        /// </summary>
        public static string AccountInformation {
            get {
                return ResourceManager.GetString("AccountInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменить пароль.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль не изменён. Пожалуйста, исправьте ошибки и попробуйте снова.
        /// </summary>
        public static string ChangingPasswordWasUnsuccessfulPleaseCorrectTheErrorsAndTryAgain {
            get {
                return ResourceManager.GetString("ChangingPasswordWasUnsuccessfulPleaseCorrectTheErrorsAndTryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to символов в длину.
        /// </summary>
        public static string CharactersInLength {
            get {
                return ResourceManager.GetString("CharactersInLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создание нового аккаунта.
        /// </summary>
        public static string CreateANewAccount {
            get {
                return ResourceManager.GetString("CreateANewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to если у Вас нет аккаунта.
        /// </summary>
        public static string IfYouDontHaveAnAccount {
            get {
                return ResourceManager.GetString("IfYouDontHaveAnAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вход.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вход не выполнен. Пожалуйста, исправьте ошибки и попробуйте снова.
        /// </summary>
        public static string LoginWasUnsuccessfulPleaseCorrectTheErrorsAndTryAgain {
            get {
                return ResourceManager.GetString("LoginWasUnsuccessfulPleaseCorrectTheErrorsAndTryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выход.
        /// </summary>
        public static string LogOff {
            get {
                return ResourceManager.GetString("LogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зарегистрируйтесь.
        /// </summary>
        public static string LogOn_Register {
            get {
                return ResourceManager.GetString("LogOn_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вход.
        /// </summary>
        public static string LogOnPartial_Login {
            get {
                return ResourceManager.GetString("LogOnPartial_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выход.
        /// </summary>
        public static string LogOnPartial_LogOff {
            get {
                return ResourceManager.GetString("LogOnPartial_LogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактировать профиль.
        /// </summary>
        public static string Manage {
            get {
                return ResourceManager.GetString("Manage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новый пароль должен быть минимум.
        /// </summary>
        public static string NewPasswordAreRequiredToBeAminimumOf {
            get {
                return ResourceManager.GetString("NewPasswordAreRequiredToBeAminimumOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменение пароля.
        /// </summary>
        public static string PasswordChanging {
            get {
                return ResourceManager.GetString("PasswordChanging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароли должны быть минимум.
        /// </summary>
        public static string PasswordsAreRequiredToBeAminimumOf {
            get {
                return ResourceManager.GetString("PasswordsAreRequiredToBeAminimumOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста, введите имя пользователя и пароль.
        /// </summary>
        public static string PleaseEnterYourUserNameAndPassword {
            get {
                return ResourceManager.GetString("PleaseEnterYourUserNameAndPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрация.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для изменения пароля используйте форму ниже.
        /// </summary>
        public static string UseTheFormBelowToChangeYourPassword {
            get {
                return ResourceManager.GetString("UseTheFormBelowToChangeYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для создания аккаунта используйте форму ниже.
        /// </summary>
        public static string UseTheFormBelowToCreateANewAccount {
            get {
                return ResourceManager.GetString("UseTheFormBelowToCreateANewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваш пароль был успешно изменён.
        /// </summary>
        public static string YourPasswordHasBeenChangedSuccessfully {
            get {
                return ResourceManager.GetString("YourPasswordHasBeenChangedSuccessfully", resourceCulture);
            }
        }
    }
}
