//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18047
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Account {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AccountViewRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AccountViewRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Account.View.AccountViewRes", typeof(AccountViewRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Аккаунт не был создан. Пожалуйста, исправьте ошибки и попробуйте снова.
        /// </summary>
        public static string Account_AccountCreatingWasUnsuccessfulPleaseCorrectTheErrorsAndTryAgain {
            get {
                return ResourceManager.GetString("Account_AccountCreatingWasUnsuccessfulPleaseCorrectTheErrorsAndTryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Учётные данные.
        /// </summary>
        public static string Account_AccountInformation {
            get {
                return ResourceManager.GetString("Account_AccountInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменить пароль.
        /// </summary>
        public static string Account_ChangePassword {
            get {
                return ResourceManager.GetString("Account_ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль не изменён. Пожалуйста, исправьте ошибки и попробуйте снова.
        /// </summary>
        public static string Account_ChangingPasswordWasUnsuccessfulPleaseCorrectTheErrorsAndTryAgain {
            get {
                return ResourceManager.GetString("Account_ChangingPasswordWasUnsuccessfulPleaseCorrectTheErrorsAndTryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to символов в длину.
        /// </summary>
        public static string Account_CharactersInLength {
            get {
                return ResourceManager.GetString("Account_CharactersInLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создание нового аккаунта.
        /// </summary>
        public static string Account_CreateANewAccount {
            get {
                return ResourceManager.GetString("Account_CreateANewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to если у Вас нет аккаунта.
        /// </summary>
        public static string Account_IfYouDontHaveAnAccount {
            get {
                return ResourceManager.GetString("Account_IfYouDontHaveAnAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вход.
        /// </summary>
        public static string Account_Login {
            get {
                return ResourceManager.GetString("Account_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зарегистрируйтесь.
        /// </summary>
        public static string Account_Login_Register {
            get {
                return ResourceManager.GetString("Account_Login_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вход.
        /// </summary>
        public static string Account_LoginPartial_Login {
            get {
                return ResourceManager.GetString("Account_LoginPartial_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выход.
        /// </summary>
        public static string Account_LoginPartial_LogOff {
            get {
                return ResourceManager.GetString("Account_LoginPartial_LogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вход не выполнен. Пожалуйста, исправьте ошибки и попробуйте снова.
        /// </summary>
        public static string Account_LoginWasUnsuccessfulPleaseCorrectTheErrorsAndTryAgain {
            get {
                return ResourceManager.GetString("Account_LoginWasUnsuccessfulPleaseCorrectTheErrorsAndTryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выход.
        /// </summary>
        public static string Account_LogOff {
            get {
                return ResourceManager.GetString("Account_LogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактировать профиль.
        /// </summary>
        public static string Account_Manage {
            get {
                return ResourceManager.GetString("Account_Manage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новый пароль должен быть минимум.
        /// </summary>
        public static string Account_NewPasswordAreRequiredToBeAminimumOf {
            get {
                return ResourceManager.GetString("Account_NewPasswordAreRequiredToBeAminimumOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменение пароля.
        /// </summary>
        public static string Account_PasswordChanging {
            get {
                return ResourceManager.GetString("Account_PasswordChanging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароли должны быть минимум.
        /// </summary>
        public static string Account_PasswordsAreRequiredToBeAminimumOf {
            get {
                return ResourceManager.GetString("Account_PasswordsAreRequiredToBeAminimumOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста, введите имя пользователя и пароль.
        /// </summary>
        public static string Account_PleaseEnterYourUserNameAndPassword {
            get {
                return ResourceManager.GetString("Account_PleaseEnterYourUserNameAndPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрация.
        /// </summary>
        public static string Account_Register {
            get {
                return ResourceManager.GetString("Account_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для изменения пароля используйте форму ниже.
        /// </summary>
        public static string Account_UseTheFormBelowToChangeYourPassword {
            get {
                return ResourceManager.GetString("Account_UseTheFormBelowToChangeYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для создания аккаунта используйте форму ниже.
        /// </summary>
        public static string Account_UseTheFormBelowToCreateANewAccount {
            get {
                return ResourceManager.GetString("Account_UseTheFormBelowToCreateANewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваш пароль был успешно изменён.
        /// </summary>
        public static string Account_YourPasswordHasBeenChangedSuccessfully {
            get {
                return ResourceManager.GetString("Account_YourPasswordHasBeenChangedSuccessfully", resourceCulture);
            }
        }
    }
}
