//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18047
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ValidationRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources._Resources.Validation.ValidationRes", typeof(ValidationRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверно указан текущий пароль или новый пароль некорректен.
        /// </summary>
        public static string Account_ChangePassword_TheCurrentPasswordIsIncorrectOrTheNewPasswordIsInvalid {
            get {
                return ResourceManager.GetString("Account_ChangePassword_TheCurrentPasswordIsIncorrectOrTheNewPasswordIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новы пароль и подтверждение не совпадают.
        /// </summary>
        public static string Account_ChangePasswordModel_PasswordAndConfirmationMismatch {
            get {
                return ResourceManager.GetString("Account_ChangePasswordModel_PasswordAndConfirmationMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверно указано имя пользователя или пароль.
        /// </summary>
        public static string Account_LogOn_TheUserNameOrPasswordProvidedIsIncorrect {
            get {
                return ResourceManager.GetString("Account_LogOn_TheUserNameOrPasswordProvidedIsIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название обязательно.
        /// </summary>
        public static string Account_NameRequired {
            get {
                return ResourceManager.GetString("Account_NameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новый пароль и подтверждение должны совпадать.
        /// </summary>
        public static string Account_NewPasswordAndConfirmMustMatch {
            get {
                return ResourceManager.GetString("Account_NewPasswordAndConfirmMustMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль и подтверждение пароля должны совпадать.
        /// </summary>
        public static string Account_PasswordAndConfirmMustMatch {
            get {
                return ResourceManager.GetString("Account_PasswordAndConfirmMustMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Минимальная длина поля &quot;{0}&quot;: {1} символа.
        /// </summary>
        public static string Account_PasswordMinLength {
            get {
                return ResourceManager.GetString("Account_PasswordMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Некорректный адрес.
        /// </summary>
        public static string Account_RegisterModel_IncorrectEmailAddress {
            get {
                return ResourceManager.GetString("Account_RegisterModel_IncorrectEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Некорректное имя пользователя.
        /// </summary>
        public static string Account_RegisterModel_IncorrectUserName {
            get {
                return ResourceManager.GetString("Account_RegisterModel_IncorrectUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль и подтверждение пароля должны совпадать.
        /// </summary>
        public static string Account_RegisterModel_PasswordsMustMatch {
            get {
                return ResourceManager.GetString("Account_RegisterModel_PasswordsMustMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле обязательно для заполнения.
        /// </summary>
        public static string Account_Required {
            get {
                return ResourceManager.GetString("Account_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле &quot;{0}&quot; должно содержать не менее {2} символов.
        /// </summary>
        public static string Account_StringLengthMin {
            get {
                return ResourceManager.GetString("Account_StringLengthMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле обязательно для заполнения.
        /// </summary>
        public static string ContentBlock_Required {
            get {
                return ResourceManager.GetString("ContentBlock_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле &quot;{0}&quot; должно содержать не более {2} символов.
        /// </summary>
        public static string ContentBlock_StringLengthMax {
            get {
                return ResourceManager.GetString("ContentBlock_StringLengthMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле обязательно для заполнения.
        /// </summary>
        public static string Event_Required {
            get {
                return ResourceManager.GetString("Event_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле &quot;{0}&quot; должно содержать не более {2} символов.
        /// </summary>
        public static string Event_StringLengthMax {
            get {
                return ResourceManager.GetString("Event_StringLengthMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле обязательно для заполнения.
        /// </summary>
        public static string Feedback_Required {
            get {
                return ResourceManager.GetString("Feedback_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле &quot;{0}&quot; должно содержать не более {2} символов.
        /// </summary>
        public static string Feedback_StringLengthMax {
            get {
                return ResourceManager.GetString("Feedback_StringLengthMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле обязательно для заполнения.
        /// </summary>
        public static string Profile_Required {
            get {
                return ResourceManager.GetString("Profile_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле &quot;{0}&quot; должно содержать не более {2} символов.
        /// </summary>
        public static string Profile_StringLengthMax {
            get {
                return ResourceManager.GetString("Profile_StringLengthMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле обязательно для заполнения.
        /// </summary>
        public static string Request_Required {
            get {
                return ResourceManager.GetString("Request_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле &quot;{0}&quot; должно содержать от {2} до {1} символов.
        /// </summary>
        public static string Request_StringLengthMinMax {
            get {
                return ResourceManager.GetString("Request_StringLengthMinMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверный формат даты.
        /// </summary>
        public static string Request_WrongDateFormat {
            get {
                return ResourceManager.GetString("Request_WrongDateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверный формат электронной почты.
        /// </summary>
        public static string Request_WrongEmailFormat {
            get {
                return ResourceManager.GetString("Request_WrongEmailFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неправильный формат.
        /// </summary>
        public static string Shared_FormatIncorrect {
            get {
                return ResourceManager.GetString("Shared_FormatIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле обязательно для заполнения.
        /// </summary>
        public static string Shared_Required {
            get {
                return ResourceManager.GetString("Shared_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле &quot;{0}&quot; должно содержать не более {2} символов.
        /// </summary>
        public static string Shared_StringLengthMax {
            get {
                return ResourceManager.GetString("Shared_StringLengthMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле &quot;{0}&quot; должно содержать не менее {2} символов.
        /// </summary>
        public static string Shared_StringLengthMin {
            get {
                return ResourceManager.GetString("Shared_StringLengthMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле обязательно для заполнения.
        /// </summary>
        public static string Sponsor_Required {
            get {
                return ResourceManager.GetString("Sponsor_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле &quot;{0}&quot; должно содержать не более {2} символов.
        /// </summary>
        public static string Sponsor_StringLengthMax {
            get {
                return ResourceManager.GetString("Sponsor_StringLengthMax", resourceCulture);
            }
        }
    }
}
