//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18047
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.ContentBlock {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ContentBlockViewRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ContentBlockViewRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ContentBlock.View.ContentBlockViewRes", typeof(ContentBlockViewRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Действия.
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Все контент-блоки.
        /// </summary>
        public static string AllContentBlocks {
            get {
                return ResourceManager.GetString("AllContentBlocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы уверены, что хотите удалить этот контент-блок?.
        /// </summary>
        public static string AreYouSureThatYouWantDeleteThisContentBlock {
            get {
                return ResourceManager.GetString("AreYouSureThatYouWantDeleteThisContentBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назад к списку.
        /// </summary>
        public static string BackToList {
            get {
                return ResourceManager.GetString("BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Контент-блок.
        /// </summary>
        public static string ContentBlock {
            get {
                return ResourceManager.GetString("ContentBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создание контент-блока.
        /// </summary>
        public static string ContentBlockCreating {
            get {
                return ResourceManager.GetString("ContentBlockCreating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удаление контент-блока.
        /// </summary>
        public static string ContentBlockDeleting {
            get {
                return ResourceManager.GetString("ContentBlockDeleting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подробности контент-блока.
        /// </summary>
        public static string ContentBlockDetails {
            get {
                return ResourceManager.GetString("ContentBlockDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактирование контент-блока.
        /// </summary>
        public static string ContentBlockEditing {
            get {
                return ResourceManager.GetString("ContentBlockEditing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Контент-блоки.
        /// </summary>
        public static string ContentBlocks {
            get {
                return ResourceManager.GetString("ContentBlocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать контент-блок.
        /// </summary>
        public static string CreateContentBlock {
            get {
                return ResourceManager.GetString("CreateContentBlock", resourceCulture);
            }
        }
    }
}
