//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18047
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Sponsors {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SponsorViewRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SponsorViewRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Sponsor.View.SponsorViewRes", typeof(SponsorViewRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Действия.
        /// </summary>
        public static string Sponsor_Actions {
            get {
                return ResourceManager.GetString("Sponsor_Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Все новости.
        /// </summary>
        public static string Sponsor_AllSponsors {
            get {
                return ResourceManager.GetString("Sponsor_AllSponsors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы уверены, что хотите удалить эту новость?.
        /// </summary>
        public static string Sponsor_AreYouSureThatYouWantDeleteThisSponsor {
            get {
                return ResourceManager.GetString("Sponsor_AreYouSureThatYouWantDeleteThisSponsor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назад к списку.
        /// </summary>
        public static string Sponsor_BackToList {
            get {
                return ResourceManager.GetString("Sponsor_BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать новость.
        /// </summary>
        public static string Sponsor_CreateSponsor {
            get {
                return ResourceManager.GetString("Sponsor_CreateSponsor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подробности новости.
        /// </summary>
        public static string Sponsor_Details {
            get {
                return ResourceManager.GetString("Sponsor_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изображение для новости.
        /// </summary>
        public static string Sponsor_ImageForSponsor {
            get {
                return ResourceManager.GetString("Sponsor_ImageForSponsor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новость.
        /// </summary>
        public static string Sponsor_Sponsor {
            get {
                return ResourceManager.GetString("Sponsor_Sponsor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создание новости.
        /// </summary>
        public static string Sponsor_SponsorCreating {
            get {
                return ResourceManager.GetString("Sponsor_SponsorCreating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удаление новости.
        /// </summary>
        public static string Sponsor_SponsorDeleting {
            get {
                return ResourceManager.GetString("Sponsor_SponsorDeleting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактирование новости.
        /// </summary>
        public static string Sponsor_SponsorEditing {
            get {
                return ResourceManager.GetString("Sponsor_SponsorEditing", resourceCulture);
            }
        }
    }
}
