//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18047
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaucasianPearl.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ViewRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ViewRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CaucasianPearl.Resources.View.ViewRes", typeof(ViewRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Об ансамбле.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактировать профиль.
        /// </summary>
        public static string Account_Manage {
            get {
                return ResourceManager.GetString("Account_Manage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Аккаунт не был создан. Пожалуйста, исправьте ошибки и попробуйте снова.
        /// </summary>
        public static string AccountCreatingWasUnsuccessfulPleaseCorrectTheErrorsAndTryAgain {
            get {
                return ResourceManager.GetString("AccountCreatingWasUnsuccessfulPleaseCorrectTheErrorsAndTryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Учётные данные.
        /// </summary>
        public static string AccountInformation {
            get {
                return ResourceManager.GetString("AccountInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Действие.
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Действия.
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить отзыв.
        /// </summary>
        public static string AddComment {
            get {
                return ResourceManager.GetString("AddComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавление отзыва.
        /// </summary>
        public static string AddingFeedback {
            get {
                return ResourceManager.GetString("AddingFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавление заявки.
        /// </summary>
        public static string AddingRequest {
            get {
                return ResourceManager.GetString("AddingRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить заявку.
        /// </summary>
        public static string AddRequest {
            get {
                return ResourceManager.GetString("AddRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Афиша.
        /// </summary>
        public static string Affiche {
            get {
                return ResourceManager.GetString("Affiche", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Все контент-блоки.
        /// </summary>
        public static string AllContentBlocks {
            get {
                return ResourceManager.GetString("AllContentBlocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Все события.
        /// </summary>
        public static string AllEvents {
            get {
                return ResourceManager.GetString("AllEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Все профили.
        /// </summary>
        public static string AllProfiles {
            get {
                return ResourceManager.GetString("AllProfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Все спонсоры.
        /// </summary>
        public static string AllSponsors {
            get {
                return ResourceManager.GetString("AllSponsors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы уверены, что хотите удалить этот контент-блок?.
        /// </summary>
        public static string AreYouSureThatYouWantDeleteThisContentBlock {
            get {
                return ResourceManager.GetString("AreYouSureThatYouWantDeleteThisContentBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы уверены, что хотите удалить это событие?.
        /// </summary>
        public static string AreYouSureThatYouWantDeleteThisEvent {
            get {
                return ResourceManager.GetString("AreYouSureThatYouWantDeleteThisEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы уверены, что хотите удалить этот профиль?.
        /// </summary>
        public static string AreYouSureThatYouWantDeleteThisProfile {
            get {
                return ResourceManager.GetString("AreYouSureThatYouWantDeleteThisProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы уверены, что хотите удалить эту заявку?.
        /// </summary>
        public static string AreYouSureThatYouWantDeleteThisRequest {
            get {
                return ResourceManager.GetString("AreYouSureThatYouWantDeleteThisRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы уверены, что хотите удалить этого спонсора?.
        /// </summary>
        public static string AreYouSureThatYouWantDeleteThisSponsor {
            get {
                return ResourceManager.GetString("AreYouSureThatYouWantDeleteThisSponsor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы уверены,что хотите удалить?.
        /// </summary>
        public static string AreYouSureYouWantToDeleteThis {
            get {
                return ResourceManager.GetString("AreYouSureYouWantToDeleteThis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы уверены, что хотите удалить эту настройку сайта?.
        /// </summary>
        public static string AreYouSureYouWantToDeleteThisSiteSetting {
            get {
                return ResourceManager.GetString("AreYouSureYouWantToDeleteThisSiteSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Авторизоваться.
        /// </summary>
        public static string Authorize {
            get {
                return ResourceManager.GetString("Authorize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вернуться на главную страницу.
        /// </summary>
        public static string BackToHomePage {
            get {
                return ResourceManager.GetString("BackToHomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назад к списку.
        /// </summary>
        public static string BackToList {
            get {
                return ResourceManager.GetString("BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стать спонсором.
        /// </summary>
        public static string BecomeSponsor {
            get {
                return ResourceManager.GetString("BecomeSponsor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отмена.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменить пароль.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль не изменён. Пожалуйста, исправьте ошибки и попробуйте снова.
        /// </summary>
        public static string ChangingPasswordWasUnsuccessfulPleaseCorrectTheErrorsAndTryAgain {
            get {
                return ResourceManager.GetString("ChangingPasswordWasUnsuccessfulPleaseCorrectTheErrorsAndTryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to символов в длину.
        /// </summary>
        public static string CharactersInLength {
            get {
                return ResourceManager.GetString("CharactersInLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Комментарий.
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Контактная информация.
        /// </summary>
        public static string ContactInformation {
            get {
                return ResourceManager.GetString("ContactInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Контакты.
        /// </summary>
        public static string Contacts {
            get {
                return ResourceManager.GetString("Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Контент-блок.
        /// </summary>
        public static string ContentBlock {
            get {
                return ResourceManager.GetString("ContentBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создание контент-блока.
        /// </summary>
        public static string ContentBlockCreating {
            get {
                return ResourceManager.GetString("ContentBlockCreating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удаление контент-блока.
        /// </summary>
        public static string ContentBlockDeleting {
            get {
                return ResourceManager.GetString("ContentBlockDeleting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подробности контент-блока.
        /// </summary>
        public static string ContentBlockDetails {
            get {
                return ResourceManager.GetString("ContentBlockDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактирование контент-блока.
        /// </summary>
        public static string ContentBlockEditing {
            get {
                return ResourceManager.GetString("ContentBlockEditing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Контент-блоки.
        /// </summary>
        public static string ContentBlocks {
            get {
                return ResourceManager.GetString("ContentBlocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обложка.
        /// </summary>
        public static string Cover {
            get {
                return ResourceManager.GetString("Cover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создание нового аккаунта.
        /// </summary>
        public static string CreateANewAccount {
            get {
                return ResourceManager.GetString("CreateANewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать контент-блок.
        /// </summary>
        public static string CreateContentBlock {
            get {
                return ResourceManager.GetString("CreateContentBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать событие.
        /// </summary>
        public static string CreateEvent {
            get {
                return ResourceManager.GetString("CreateEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать профиль.
        /// </summary>
        public static string CreateProfile {
            get {
                return ResourceManager.GetString("CreateProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать спонсора.
        /// </summary>
        public static string CreateSponsor {
            get {
                return ResourceManager.GetString("CreateSponsor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать профиль пользователя.
        /// </summary>
        public static string CreateUserProfile {
            get {
                return ResourceManager.GetString("CreateUserProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создание.
        /// </summary>
        public static string Creating {
            get {
                return ResourceManager.GetString("Creating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Значение по умолчанию.
        /// </summary>
        public static string DefaultValue {
            get {
                return ResourceManager.GetString("DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удаление.
        /// </summary>
        public static string Deleting {
            get {
                return ResourceManager.GetString("Deleting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Описание.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подробности.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вниз.
        /// </summary>
        public static string Down {
            get {
                return ResourceManager.GetString("Down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактировать.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактирование.
        /// </summary>
        public static string Editing {
            get {
                return ResourceManager.GetString("Editing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Событие.
        /// </summary>
        public static string Event {
            get {
                return ResourceManager.GetString("Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создание события.
        /// </summary>
        public static string EventCreating {
            get {
                return ResourceManager.GetString("EventCreating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удаление события.
        /// </summary>
        public static string EventDeleting {
            get {
                return ResourceManager.GetString("EventDeleting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подробности событие.
        /// </summary>
        public static string EventDetails {
            get {
                return ResourceManager.GetString("EventDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактирование события.
        /// </summary>
        public static string EventEditing {
            get {
                return ResourceManager.GetString("EventEditing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to События.
        /// </summary>
        public static string Events {
            get {
                return ResourceManager.GetString("Events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отзыв.
        /// </summary>
        public static string Feedback {
            get {
                return ResourceManager.GetString("Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удаление отзыва.
        /// </summary>
        public static string FeedbackDeleting {
            get {
                return ResourceManager.GetString("FeedbackDeleting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подробности отзыва.
        /// </summary>
        public static string FeedbackDetails {
            get {
                return ResourceManager.GetString("FeedbackDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактирование отзыва.
        /// </summary>
        public static string FeedbackEditing {
            get {
                return ResourceManager.GetString("FeedbackEditing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отзывы.
        /// </summary>
        public static string Feedbacks {
            get {
                return ResourceManager.GetString("Feedbacks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Во время отправки отзыва возникла неожиданная ошибка. Пожалуйста, повторите попытку позднее..
        /// </summary>
        public static string FeedbackSendingError {
            get {
                return ResourceManager.GetString("FeedbackSendingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Спасибо за Ваше мнение! Отзыв появится на сайте после проверки модератором..
        /// </summary>
        public static string FeedbackThanks {
            get {
                return ResourceManager.GetString("FeedbackThanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to © Ансамбль «Жемчужина Кавказа».
        /// </summary>
        public static string FooterTitle {
            get {
                return ResourceManager.GetString("FooterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Галерея.
        /// </summary>
        public static string Gallery {
            get {
                return ResourceManager.GetString("Gallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Домашняя.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройка режима главной страницы.
        /// </summary>
        public static string HomePageModeSettings {
            get {
                return ResourceManager.GetString("HomePageModeSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to если у Вас нет аккаунта.
        /// </summary>
        public static string IfYouDontHaveAnAccount {
            get {
                return ResourceManager.GetString("IfYouDontHaveAnAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изображение для события.
        /// </summary>
        public static string ImageForEvent {
            get {
                return ResourceManager.GetString("ImageForEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изображение для профиля.
        /// </summary>
        public static string ImageForProfile {
            get {
                return ResourceManager.GetString("ImageForProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изображение для спонсора.
        /// </summary>
        public static string ImageForSponsor {
            get {
                return ResourceManager.GetString("ImageForSponsor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Главная.
        /// </summary>
        public static string Index {
            get {
                return ResourceManager.GetString("Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вход.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зарегистрируйтесь.
        /// </summary>
        public static string Login_Register {
            get {
                return ResourceManager.GetString("Login_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вход.
        /// </summary>
        public static string LoginPartial_Login {
            get {
                return ResourceManager.GetString("LoginPartial_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вход не выполнен. Пожалуйста, исправьте ошибки и попробуйте снова.
        /// </summary>
        public static string LoginWasUnsuccessfulPleaseCorrectTheErrorsAndTryAgain {
            get {
                return ResourceManager.GetString("LoginWasUnsuccessfulPleaseCorrectTheErrorsAndTryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выход.
        /// </summary>
        public static string LogOff {
            get {
                return ResourceManager.GetString("LogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Управление аккаунтом.
        /// </summary>
        public static string ManageAccount {
            get {
                return ResourceManager.GetString("ManageAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Управление профилем.
        /// </summary>
        public static string ManageProfile {
            get {
                return ResourceManager.GetString("ManageProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ансамбль национального танца под руководством Вердян Жанны Геннадьевны.
        /// </summary>
        public static string MetaAboutOgDescription {
            get {
                return ResourceManager.GetString("MetaAboutOgDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.caucasian-pearl.ru/content/img/site/social_share/aboutOgImage.png.
        /// </summary>
        public static string MetaAboutOgImage {
            get {
                return ResourceManager.GetString("MetaAboutOgImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ансамбль национального танца — «Жемчужина Кавказа».
        /// </summary>
        public static string MetaAboutOgTitle {
            get {
                return ResourceManager.GetString("MetaAboutOgTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ансамбль национального танца под руководством Вердян Жанны Геннадьевны.
        /// </summary>
        public static string MetaAfficheOgDescription {
            get {
                return ResourceManager.GetString("MetaAfficheOgDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.caucasian-pearl.ru/content/img/site/social_share/afficheOgImage.png.
        /// </summary>
        public static string MetaAfficheOgImage {
            get {
                return ResourceManager.GetString("MetaAfficheOgImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ансамбль национального танца — «Жемчужина Кавказа».
        /// </summary>
        public static string MetaAfficheOgTitle {
            get {
                return ResourceManager.GetString("MetaAfficheOgTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ансамбль национального танца под руководством Вердян Жанны Геннадьевны.
        /// </summary>
        public static string MetaDefaultOgDescription {
            get {
                return ResourceManager.GetString("MetaDefaultOgDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.caucasian-pearl.ru/content/img/site/social_share/defaultOgImage.png.
        /// </summary>
        public static string MetaDefaultOgImage {
            get {
                return ResourceManager.GetString("MetaDefaultOgImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ансамбль национального танца — «Жемчужина Кавказа».
        /// </summary>
        public static string MetaDefaultOgTitle {
            get {
                return ResourceManager.GetString("MetaDefaultOgTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ансамбль национального танца под руководством Вердян Жанны Геннадьевны.
        /// </summary>
        public static string MetaDescription {
            get {
                return ResourceManager.GetString("MetaDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ансамбль национального танца под руководством Вердян Жанны Геннадьевны.
        /// </summary>
        public static string MetaEventsOgDescription {
            get {
                return ResourceManager.GetString("MetaEventsOgDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.caucasian-pearl.ru/content/img/site/social_share/eventsOgImage.png.
        /// </summary>
        public static string MetaEventsOgImage {
            get {
                return ResourceManager.GetString("MetaEventsOgImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ансамбль национального танца — «Жемчужина Кавказа».
        /// </summary>
        public static string MetaEventsOgTitle {
            get {
                return ResourceManager.GetString("MetaEventsOgTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ансамбль национального танца под руководством Вердян Жанны Геннадьевны.
        /// </summary>
        public static string MetaHomeOgDescription {
            get {
                return ResourceManager.GetString("MetaHomeOgDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.caucasian-pearl.ru/content/img/site/social_share/homeOgImage.png.
        /// </summary>
        public static string MetaHomeOgImage {
            get {
                return ResourceManager.GetString("MetaHomeOgImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ансамбль национального танца — «Жемчужина Кавказа».
        /// </summary>
        public static string MetaHomeOgTitle {
            get {
                return ResourceManager.GetString("MetaHomeOgTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ансамбль,кавказ,танцы,выступление,народный.
        /// </summary>
        public static string MetaKeyWords {
            get {
                return ResourceManager.GetString("MetaKeyWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новый пароль должен быть минимум.
        /// </summary>
        public static string NewPasswordAreRequiredToBeAminimumOf {
            get {
                return ResourceManager.GetString("NewPasswordAreRequiredToBeAminimumOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не найдено ни одного фотоальбома..
        /// </summary>
        public static string NoPhotosetsFound {
            get {
                return ResourceManager.GetString("NoPhotosetsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не указано.
        /// </summary>
        public static string NotSpecified {
            get {
                return ResourceManager.GetString("NotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наш коллектив.
        /// </summary>
        public static string OurTeam {
            get {
                return ResourceManager.GetString("OurTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменение пароля.
        /// </summary>
        public static string PasswordChanging {
            get {
                return ResourceManager.GetString("PasswordChanging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароли должны быть минимум.
        /// </summary>
        public static string PasswordsAreRequiredToBeAminimumOf {
            get {
                return ResourceManager.GetString("PasswordsAreRequiredToBeAminimumOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль успешно сброшен. Установлен пароль по умолчанию.
        /// </summary>
        public static string PasswordSuccessfullyReseted {
            get {
                return ResourceManager.GetString("PasswordSuccessfullyReseted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фотоальбомы.
        /// </summary>
        public static string Photosets {
            get {
                return ResourceManager.GetString("Photosets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста, введите имя пользователя и пароль.
        /// </summary>
        public static string PleaseEnterYourUserNameAndPassword {
            get {
                return ResourceManager.GetString("PleaseEnterYourUserNameAndPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создание профиля.
        /// </summary>
        public static string ProfileCreating {
            get {
                return ResourceManager.GetString("ProfileCreating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удаление профиля.
        /// </summary>
        public static string ProfileDeleting {
            get {
                return ResourceManager.GetString("ProfileDeleting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подробности профиля.
        /// </summary>
        public static string ProfileDetails {
            get {
                return ResourceManager.GetString("ProfileDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактирование профиля.
        /// </summary>
        public static string ProfileEditing {
            get {
                return ResourceManager.GetString("ProfileEditing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Профили.
        /// </summary>
        public static string Profiles {
            get {
                return ResourceManager.GetString("Profiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Жемчужина Кавказа.
        /// </summary>
        public static string ProjectTitle {
            get {
                return ResourceManager.GetString("ProjectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ЖК.
        /// </summary>
        public static string ProjectTitleShort {
            get {
                return ResourceManager.GetString("ProjectTitleShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрация.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрация нового пользователя.
        /// </summary>
        public static string RegisterNewAccount {
            get {
                return ResourceManager.GetString("RegisterNewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удаление заявки.
        /// </summary>
        public static string RequestDeleting {
            get {
                return ResourceManager.GetString("RequestDeleting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подробности заявки.
        /// </summary>
        public static string RequestDetails {
            get {
                return ResourceManager.GetString("RequestDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактирование заявки.
        /// </summary>
        public static string RequestEditing {
            get {
                return ResourceManager.GetString("RequestEditing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заявки.
        /// </summary>
        public static string Requests {
            get {
                return ResourceManager.GetString("Requests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Во время отправки заявки возникла неожиданная ошибка. Пожалуйста, повторите попытку позднее..
        /// </summary>
        public static string RequestSendingError {
            get {
                return ResourceManager.GetString("RequestSendingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Спасибо за проявленный интерес! Мы обязательно с Вами свяжемся!.
        /// </summary>
        public static string RequestThanks {
            get {
                return ResourceManager.GetString("RequestThanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сбросить пароль.
        /// </summary>
        public static string ResetPassword {
            get {
                return ResourceManager.GetString("ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Роль.
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Роли.
        /// </summary>
        public static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Разделы.
        /// </summary>
        public static string Sections {
            get {
                return ResourceManager.GetString("Sections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оставить отзыв.
        /// </summary>
        public static string SendFeedback {
            get {
                return ResourceManager.GetString("SendFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оставить заявку.
        /// </summary>
        public static string SendRequest {
            get {
                return ResourceManager.GetString("SendRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оставить заявку на выступление.
        /// </summary>
        public static string SendRequestForPerformance {
            get {
                return ResourceManager.GetString("SendRequestForPerformance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Установить пароль.
        /// </summary>
        public static string SetPassword {
            get {
                return ResourceManager.GetString("SetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройка сайта.
        /// </summary>
        public static string SiteSetting {
            get {
                return ResourceManager.GetString("SiteSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удаление настройки сайта.
        /// </summary>
        public static string SiteSettingDeleting {
            get {
                return ResourceManager.GetString("SiteSettingDeleting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройки сайта.
        /// </summary>
        public static string SiteSettings {
            get {
                return ResourceManager.GetString("SiteSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Спонсор.
        /// </summary>
        public static string Sponsor {
            get {
                return ResourceManager.GetString("Sponsor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создание спонсора.
        /// </summary>
        public static string SponsorCreating {
            get {
                return ResourceManager.GetString("SponsorCreating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удаление спонсора.
        /// </summary>
        public static string SponsorDeleting {
            get {
                return ResourceManager.GetString("SponsorDeleting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подробности спонсора.
        /// </summary>
        public static string SponsorDetails {
            get {
                return ResourceManager.GetString("SponsorDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактирование спонсора.
        /// </summary>
        public static string SponsorEditing {
            get {
                return ResourceManager.GetString("SponsorEditing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Спонсоры.
        /// </summary>
        public static string Sponsors {
            get {
                return ResourceManager.GetString("Sponsors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Спасибо.
        /// </summary>
        public static string Thanks {
            get {
                return ResourceManager.GetString("Thanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Спасибо! Мы с Вами обязательно свяжемся!.
        /// </summary>
        public static string ThankYouWeWillCertainlyContactYou {
            get {
                return ResourceManager.GetString("ThankYouWeWillCertainlyContactYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to На главную.
        /// </summary>
        public static string ToHomePage {
            get {
                return ResourceManager.GetString("ToHomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зарегистрируйтесь.
        /// </summary>
        public static string ToRegister {
            get {
                return ResourceManager.GetString("ToRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вверх.
        /// </summary>
        public static string Up {
            get {
                return ResourceManager.GetString("Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузить.
        /// </summary>
        public static string Upload {
            get {
                return ResourceManager.GetString("Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователь не имеет ни одной роли.
        /// </summary>
        public static string UserDontHaveAnyRole {
            get {
                return ResourceManager.GetString("UserDontHaveAnyRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Профиль пользователя.
        /// </summary>
        public static string UserProfile {
            get {
                return ResourceManager.GetString("UserProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Профили пользователей.
        /// </summary>
        public static string UserProfiles {
            get {
                return ResourceManager.GetString("UserProfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для изменения пароля используйте форму ниже.
        /// </summary>
        public static string UseTheFormBelowToChangeYourPassword {
            get {
                return ResourceManager.GetString("UseTheFormBelowToChangeYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для создания аккаунта используйте форму ниже.
        /// </summary>
        public static string UseTheFormBelowToCreateANewAccount {
            get {
                return ResourceManager.GetString("UseTheFormBelowToCreateANewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Значение.
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Написать нам.
        /// </summary>
        public static string WriteUs {
            get {
                return ResourceManager.GetString("WriteUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы вошли как.
        /// </summary>
        public static string YouLoggedInAs {
            get {
                return ResourceManager.GetString("YouLoggedInAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваш пароль был изменён..
        /// </summary>
        public static string YourPasswordHasBeenChanged {
            get {
                return ResourceManager.GetString("YourPasswordHasBeenChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваш пароль был успешно изменён.
        /// </summary>
        public static string YourPasswordHasBeenChangedSuccessfully {
            get {
                return ResourceManager.GetString("YourPasswordHasBeenChangedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваш пароль был установлен..
        /// </summary>
        public static string YourPasswordHasBeenSet {
            get {
                return ResourceManager.GetString("YourPasswordHasBeenSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы уверены, что хотите удалить?.
        /// </summary>
        public static string YouSureYouWantToDeleteThis {
            get {
                return ResourceManager.GetString("YouSureYouWantToDeleteThis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы уверены, что хотите удалить этот отзыв?.
        /// </summary>
        public static string YouSureYouWantToDeleteThisFeedback {
            get {
                return ResourceManager.GetString("YouSureYouWantToDeleteThisFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы уверены, что хотите удалить эту настройку сайта?.
        /// </summary>
        public static string YouSureYouWantToDeleteThisSiteSettings {
            get {
                return ResourceManager.GetString("YouSureYouWantToDeleteThisSiteSettings", resourceCulture);
            }
        }
    }
}
