//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18047
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ModelRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ModelRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources._Resources.Model.ModelRes", typeof(ModelRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтверждение нового пароля.
        /// </summary>
        public static string Account_ChangePasswordModel_ConfirmNewPassword {
            get {
                return ResourceManager.GetString("Account_ChangePasswordModel_ConfirmNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текущий пароль.
        /// </summary>
        public static string Account_ChangePasswordModel_CurrentPassword {
            get {
                return ResourceManager.GetString("Account_ChangePasswordModel_CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новый пароль.
        /// </summary>
        public static string Account_ChangePasswordModel_NewPassword {
            get {
                return ResourceManager.GetString("Account_ChangePasswordModel_NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль.
        /// </summary>
        public static string Account_LogOnModel_Password {
            get {
                return ResourceManager.GetString("Account_LogOnModel_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запомнить?.
        /// </summary>
        public static string Account_LogOnModel_RememberMe {
            get {
                return ResourceManager.GetString("Account_LogOnModel_RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя пользователя.
        /// </summary>
        public static string Account_LogOnModel_UserName {
            get {
                return ResourceManager.GetString("Account_LogOnModel_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название.
        /// </summary>
        public static string Account_Name {
            get {
                return ResourceManager.GetString("Account_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтверждение пароля.
        /// </summary>
        public static string Account_RegisterModel_ConfirmPassword {
            get {
                return ResourceManager.GetString("Account_RegisterModel_ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Адрес почты.
        /// </summary>
        public static string Account_RegisterModel_Email {
            get {
                return ResourceManager.GetString("Account_RegisterModel_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль.
        /// </summary>
        public static string Account_RegisterModel_Password {
            get {
                return ResourceManager.GetString("Account_RegisterModel_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя пользователя.
        /// </summary>
        public static string Account_RegisterModel_UserName {
            get {
                return ResourceManager.GetString("Account_RegisterModel_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID контент-блока.
        /// </summary>
        public static string ContentBlock_BlockId {
            get {
                return ResourceManager.GetString("ContentBlock_BlockId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Контент.
        /// </summary>
        public static string ContentBlock_Content {
            get {
                return ResourceManager.GetString("ContentBlock_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Описание.
        /// </summary>
        public static string ContentBlock_Description {
            get {
                return ResourceManager.GetString("ContentBlock_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Опубликован.
        /// </summary>
        public static string ContentBlock_IsPublished {
            get {
                return ResourceManager.GetString("ContentBlock_IsPublished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID блока расположения.
        /// </summary>
        public static string ContentBlock_PlaceHolderId {
            get {
                return ResourceManager.GetString("ContentBlock_PlaceHolderId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Город.
        /// </summary>
        public static string Feedback_City {
            get {
                return ResourceManager.GetString("Feedback_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отзыв.
        /// </summary>
        public static string Feedback_Comment {
            get {
                return ResourceManager.GetString("Feedback_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата и время.
        /// </summary>
        public static string Feedback_FeedbackDateTime {
            get {
                return ResourceManager.GetString("Feedback_FeedbackDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Утверждён.
        /// </summary>
        public static string Feedback_IsApproved {
            get {
                return ResourceManager.GetString("Feedback_IsApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя.
        /// </summary>
        public static string Feedback_Name {
            get {
                return ResourceManager.GetString("Feedback_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предложения.
        /// </summary>
        public static string Feedback_Suggestion {
            get {
                return ResourceManager.GetString("Feedback_Suggestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваш город.
        /// </summary>
        public static string Feedback_YourCity {
            get {
                return ResourceManager.GetString("Feedback_YourCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваше имя.
        /// </summary>
        public static string Feedback_YourName {
            get {
                return ResourceManager.GetString("Feedback_YourName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Адрес почты.
        /// </summary>
        public static string Profile_Email {
            get {
                return ResourceManager.GetString("Profile_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя.
        /// </summary>
        public static string Profile_FirstName {
            get {
                return ResourceManager.GetString("Profile_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фамилия.
        /// </summary>
        public static string Profile_LastName {
            get {
                return ResourceManager.GetString("Profile_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя пользователя.
        /// </summary>
        public static string Profile_UserName {
            get {
                return ResourceManager.GetString("Profile_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Город.
        /// </summary>
        public static string Request_City {
            get {
                return ResourceManager.GetString("Request_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Комментарий.
        /// </summary>
        public static string Request_Comment {
            get {
                return ResourceManager.GetString("Request_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текст заявки.
        /// </summary>
        public static string Request_Content {
            get {
                return ResourceManager.GetString("Request_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата и время регистрации заявки.
        /// </summary>
        public static string Request_Created {
            get {
                return ResourceManager.GetString("Request_Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Электронная почта.
        /// </summary>
        public static string Request_Email {
            get {
                return ResourceManager.GetString("Request_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя.
        /// </summary>
        public static string Request_Name {
            get {
                return ResourceManager.GetString("Request_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не обработано.
        /// </summary>
        public static string Request_NotProcessed {
            get {
                return ResourceManager.GetString("Request_NotProcessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Телефон.
        /// </summary>
        public static string Request_Phone {
            get {
                return ResourceManager.GetString("Request_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обработано.
        /// </summary>
        public static string Request_Processed {
            get {
                return ResourceManager.GetString("Request_Processed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Желаемая дата.
        /// </summary>
        public static string Request_RequestDate {
            get {
                return ResourceManager.GetString("Request_RequestDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статус.
        /// </summary>
        public static string Request_Status {
            get {
                return ResourceManager.GetString("Request_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваш город.
        /// </summary>
        public static string Request_YourCity {
            get {
                return ResourceManager.GetString("Request_YourCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваше имя.
        /// </summary>
        public static string Request_YourName {
            get {
                return ResourceManager.GetString("Request_YourName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Город.
        /// </summary>
        public static string Sponsor_City {
            get {
                return ResourceManager.GetString("Sponsor_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Комментарий.
        /// </summary>
        public static string Sponsor_Comment {
            get {
                return ResourceManager.GetString("Sponsor_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата и время регистрации заявки.
        /// </summary>
        public static string Sponsor_Created {
            get {
                return ResourceManager.GetString("Sponsor_Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Электронная почта.
        /// </summary>
        public static string Sponsor_Email {
            get {
                return ResourceManager.GetString("Sponsor_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя.
        /// </summary>
        public static string Sponsor_Name {
            get {
                return ResourceManager.GetString("Sponsor_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Телефон.
        /// </summary>
        public static string Sponsor_Phone {
            get {
                return ResourceManager.GetString("Sponsor_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статус.
        /// </summary>
        public static string Sponsor_Status {
            get {
                return ResourceManager.GetString("Sponsor_Status", resourceCulture);
            }
        }
    }
}
