//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18047
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaucasianPearl.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ValidationRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CaucasianPearl.Resources.Validation.ValidationRes", typeof(ValidationRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверно указан текущий пароль или новый пароль некорректен.
        /// </summary>
        public static string Account_ChangePassword_TheCurrentPasswordIsIncorrectOrTheNewPasswordIsInvalid {
            get {
                return ResourceManager.GetString("Account_ChangePassword_TheCurrentPasswordIsIncorrectOrTheNewPasswordIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название обязательно.
        /// </summary>
        public static string Account_NameRequired {
            get {
                return ResourceManager.GetString("Account_NameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Минимальная длина поля &quot;{0}&quot;: {1} символа.
        /// </summary>
        public static string Account_PasswordMinLength {
            get {
                return ResourceManager.GetString("Account_PasswordMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Некорректный электронной почты.
        /// </summary>
        public static string IncorrectEmailAddress {
            get {
                return ResourceManager.GetString("IncorrectEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неправильный формат.
        /// </summary>
        public static string IncorrectFormat {
            get {
                return ResourceManager.GetString("IncorrectFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Некорректное имя пользователя.
        /// </summary>
        public static string IncorrectUserName {
            get {
                return ResourceManager.GetString("IncorrectUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Максимальная сумма - {1} рублей.
        /// </summary>
        public static string MaxSum {
            get {
                return ResourceManager.GetString("MaxSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Минимальная сумма - {1} рублей.
        /// </summary>
        public static string MinSum {
            get {
                return ResourceManager.GetString("MinSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новый пароль и подтверждение должны совпадать.
        /// </summary>
        public static string NewPasswordAndConfirmMustMatch {
            get {
                return ResourceManager.GetString("NewPasswordAndConfirmMustMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новый пароль и подтверждение не совпадают.
        /// </summary>
        public static string PasswordAndConfirmationMismatch {
            get {
                return ResourceManager.GetString("PasswordAndConfirmationMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль и подтверждение пароля должны совпадать.
        /// </summary>
        public static string PasswordsMustMatch {
            get {
                return ResourceManager.GetString("PasswordsMustMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле обязательно для заполнения.
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Только маленькие латинские буквы, цифры и подчёркивание.
        /// </summary>
        public static string ShortNameRegex {
            get {
                return ResourceManager.GetString("ShortNameRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле &quot;{0}&quot; должно содержать не более {1} символов.
        /// </summary>
        public static string StringLengthMax {
            get {
                return ResourceManager.GetString("StringLengthMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле &quot;{0}&quot; должно содержать не менее {2} символов.
        /// </summary>
        public static string StringLengthMin {
            get {
                return ResourceManager.GetString("StringLengthMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле &quot;{0}&quot; должно содержать от {2} до {1} символов.
        /// </summary>
        public static string StringLengthMinMax {
            get {
                return ResourceManager.GetString("StringLengthMinMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сумма должна быть между {1} и {2} рублей.
        /// </summary>
        public static string SumRange {
            get {
                return ResourceManager.GetString("SumRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверно указано имя пользователя или пароль.
        /// </summary>
        public static string TheUserNameOrPasswordProvidedIsIncorrect {
            get {
                return ResourceManager.GetString("TheUserNameOrPasswordProvidedIsIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверный формат ссылки.
        /// </summary>
        public static string Url {
            get {
                return ResourceManager.GetString("Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверный формат даты.
        /// </summary>
        public static string WrongDateFormat {
            get {
                return ResourceManager.GetString("WrongDateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверный формат электронной почты.
        /// </summary>
        public static string WrongEmailFormat {
            get {
                return ResourceManager.GetString("WrongEmailFormat", resourceCulture);
            }
        }
    }
}
