//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaucasianPearl.Models.EDM
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CaucasianPearlContext : DbContext
    {
        public CaucasianPearlContext()
            : base("name=CaucasianPearlContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Event> Events { get; set; }
        public DbSet<Feedback> Feedbacks { get; set; }
        public DbSet<Request> Requests { get; set; }
        public DbSet<Profile> Profiles { get; set; }
        public DbSet<ContentBlock> ContentBlocks { get; set; }
        public DbSet<EventMedia> EventMedias { get; set; }
        public DbSet<SiteSetting> SiteSettings { get; set; }
        public DbSet<Sponsor> Sponsors { get; set; }
    }
}
