//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaucasianPearl.Models.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventMedia
    {
        public int ID { get; set; }
        public Nullable<int> EventId { get; set; }
        public string PhotoId { get; set; }
        public string PhotosetId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string MediaType { get; set; }
        public string FlickrUrl { get; set; }
        public string ThumbnailUrl { get; set; }
        public string SmallUrl { get; set; }
        public string MediumUrl { get; set; }
        public string LargeUrl { get; set; }
        public string VideoUrl { get; set; }
        public Nullable<bool> IsPrimary { get; set; }
        public Nullable<int> Sequence { get; set; }
    
        public virtual Event Event { get; set; }
    }
}
