//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaucasianPearl.Models.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class OneNews
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.TimeSpan> CreatedTime { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
        public Nullable<System.TimeSpan> LastUpdatedTime { get; set; }
        public string LastUpdatedUser { get; set; }
        public string Content { get; set; }
        public string ImageExt { get; set; }
        public string ShortName { get; set; }
        public Nullable<int> Sequence { get; set; }
    }
}
